# Generated by Django 4.1 on 2022-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_amenity_facility_houserule_roomtype_room_amenities_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "Facilities"},
        ),
        migrations.AlterModelOptions(
            name="houserule",
            options={"verbose_name": "House Rule"},
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={"verbose_name": "Room Type"},
        ),
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="rooms.amenity"),
        ),
        migrations.AlterField(
            model_name="room",
            name="facility",
            field=models.ManyToManyField(blank=True, to="rooms.facility"),
        ),
        migrations.AlterField(
            model_name="room",
            name="house_rules",
            field=models.ManyToManyField(blank=True, to="rooms.houserule"),
        ),
    ]
