# Generated by Django 4.1 on 2022-09-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
