# Generated by Django 4.1.1 on 2022-09-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_photo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bath',
            new_name='baths',
        ),
    ]
